{% set name = "pynufft" %}
{% set version = "2022.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynufft-{{ version }}.tar.gz
  sha256: 99cd34f1ff181e66ad50649783cf18d102eb39834aaebc4e190a0c9dcb8d1ea5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - python >=3.6
    - scipy

test:
  imports:
    - pynufft
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jyhmiinlin/pynufft
  summary: Python non-uniform fast Fourier transform (PyNUFFT)
  license: AGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nehaljwani
