{% set name = "pynufft" %}
{% set version = "2024.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pynufft-{{ version }}.tar.gz
  sha256: 1c1d52eab5c74e2fb7b13d08ae7b8d51accb6ae29d0d1bb84e4e7f3f0c43c501

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - numpy
    - python >={{ python_min }}
    - scipy

test:
  imports:
    - pynufft
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jyhmiinlin/pynufft
  summary: Python non-uniform fast Fourier transform (PyNUFFT)
  license: AGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nehaljwani
