{% set name = "pynufft" %}
{% set version = "2024.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynufft-{{ version }}.tar.gz
  sha256: 8111bb964a4488f2d3d12877f4474e1a330ac00e36b68358a05d49f88317dbef

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - python >=3.6
    - scipy

test:
  imports:
    - pynufft
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jyhmiinlin/pynufft
  summary: Python non-uniform fast Fourier transform (PyNUFFT)
  license: AGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nehaljwani
