{% set name = "pynufft" %}
{% set version = "2022.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynufft-{{ version }}.tar.gz
  sha256: fa823dc140640edfb52439661240c342c985fa9a17e6b44327ebe69b62eafafd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - python >=3.6
    - scipy

test:
  imports:
    - pynufft
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jyhmiinlin/pynufft
  summary: Python non-uniform fast Fourier transform (PyNUFFT)
  license: AGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nehaljwani
